In [19]:
# loaded_model = pickle.load("squeezenetfinetuned.pkl")
import sklearn 
import numpy as np
import joblib
import pickle
import torch

#Basma
# classifer = joblib.load("C:/Users/basma/Fourth Year/Graduation_Project/squeezenetfinetuned.pkl")

#Bassem
# classifer = joblib.load("squeezenetuntrained.pkl")

model = pickle.load(open('new squeezenet(finetuned).pkl', 'rb'))
model.eval()

SqueezeNet(
  (features): Sequential(
    (0): Conv2d(3, 96, kernel_size=(7, 7), stride=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
    (3): Fire(
      (squeeze): Conv2d(96, 16, kernel_size=(1, 1), stride=(1, 1))
      (squeeze_activation): ReLU(inplace=True)
      (expand1x1): Conv2d(16, 64, kernel_size=(1, 1), stride=(1, 1))
      (expand1x1_activation): ReLU(inplace=True)
      (expand3x3): Conv2d(16, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (expand3x3_activation): ReLU(inplace=True)
    )
    (4): Fire(
      (squeeze): Conv2d(128, 16, kernel_size=(1, 1), stride=(1, 1))
      (squeeze_activation): ReLU(inplace=True)
      (expand1x1): Conv2d(16, 64, kernel_size=(1, 1), stride=(1, 1))
      (expand1x1_activation): ReLU(inplace=True)
      (expand3x3): Conv2d(16, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (expand3x3_activation): ReLU(inplace=True)
    )
    (5): Fire(
   

In [9]:
# # Segmentation then Cropping algorithm 
# import cv2
# from imutils import contours
# from skimage.filters import threshold_otsu

# # Load image, grayscale, Otsu's threshold
# image_array = []
# results = []
# # image = cv2.imread('C:/Users/basma/Fourth Year/Graduation_Project/O001 (1).png')
# # image_array.append(image)
# # gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
# # thresh = cv2.threshold(gray,0,255,cv2.THRESH_OTSU + cv2.THRESH_BINARY)[1]
# # inv = cv2.bitwise_not(thresh)
# # rgb = cv2.cvtColor(inv, cv2.COLOR_GRAY2RGB)

# # Load image
# image = cv2.imread('walk (1).png')

# # Convert image to grayscale
# gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# # Threshold image
# _, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)

# # Find contours
# contours,_  = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)


# #---------------------------------------------------------------------
# # def Otsu(myImage):

#   # image = cv2.imread(myImage)
#   # gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#   # thresh = cv2.threshold(gray,0,255,cv2.THRESH_OTSU + cv2.THRESH_BINARY)[1]
#   # inv = cv2.bitwise_not(thresh)
#   # rgb = cv2.cvtColor(inv, cv2.COLOR_GRAY2RGB)
#   # # image_array.append(rgb)

#   # return inv








#   # sample_image = cv2.imread(myImage)
#   # img = cv2.cvtColor(sample_image,cv2.COLOR_BGR2RGB)

#   # # plt.axis('off')
#   # # plt.imshow(img)

#   # img_gray=cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)

#   # thresh = threshold_otsu(img_gray)
#   # img_otsu  = img_gray < thresh

#   # # plt.imshow(img_otsu)

#   # filtered = filter_image(img, img_otsu)
#   # filteredBW=cv2.cvtColor(filtered,cv2.COLOR_RGB2GRAY)
#   # return filteredBW



# def filter_image(image, mask):

#     r = image[:,:,0] * mask
#     g = image[:,:,1] * mask
#     b = image[:,:,2] * mask

#     return np.dstack([r,g,b])

# # image = Otsu('D:/semester 7/Graduation Project/Datasets/new dataset/O001.png')

# # gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
# # thresh = cv2.threshold(gray,0,255,cv2.THRESH_OTSU + cv2.THRESH_BINARY)[1]
# # inv = cv2.bitwise_not(thresh)

# cv2.imwrite('image2.png', image)
# #---------------------------------------------------------------------

# # Find contours, sort from left-to-right, then crop
# # cnts = cv2.findContours(image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
# # cnts = cnts[0] if len(cnts) == 2 else cnts[1]
# # cnts, _ = contours.sort_contours(cnts, method="left-to-right")

# # ROI_number = 0
# # for c in cnts:
# #     area = cv2.contourArea(c)
# #     if area > 50:
# #         x,y,w,h = cv2.boundingRect(c)
# #         ROI = 255 - image[y:y+h, x:x+w]
# #         # img1 = cv2.copyMakeBorder(ROI, 20,20,20,20,cv2.BORDER_CONSTANT, value=[255,255,255])
# #         img2 = cv2.bitwise_not(ROI)
# #         cv2.imwrite('ROIVVV_{}.png'.format(ROI_number), img2)
        
# #         image_array.append(img2)
# #         cv2.rectangle(image, (x, y), (x + w, y + h), (36,255,12), 2)
# #         ROI_number += 1










# # Crop symbols
# for i, contour in enumerate(contours):
#     # Get bounding rectangle
#     x, y, w, h = cv2.boundingRect(contour)

#     # Crop symbol
#     symbol = image[y:y+h, x:x+w]

#     # image = cv2.imread(symbol)
#     gray = cv2.cvtColor(symbol, cv2.COLOR_BGR2GRAY)
#     thresh = cv2.threshold(gray,0,255,cv2.THRESH_OTSU + cv2.THRESH_BINARY)[1]
#     inv = cv2.bitwise_not(thresh)

#     # Save symbol
#     cv2.imwrite(f"symbol{i}.png", inv)





In [25]:
import cv2
import numpy as np
import os

# Load the YOLOv3 network
net = cv2.dnn.readNet("yolov3.weights", "yolov3.cfg")

# Set confidence threshold and non-maximum suppression threshold for YOLO
conf_threshold = 0.5
nms_threshold = 0.4

# Load the input image
image = cv2.imread("walk.png")

# Convert image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Threshold image
_, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)

# Find contours
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)


# Iterate over the contours
for i, contour in enumerate(contours):
    # Get bounding box coordinates
    x, y, w, h = cv2.boundingRect(contour)

    # Crop the image using the bounding box coordinates
    crop_img = image[y:y+h, x:x+w]

    # Create a blob from the cropped image
    blob = cv2.dnn.blobFromImage(crop_img, 1 / 255.0, (416, 416), swapRB=True, crop=False)

    # Pass the blob through the network to perform object detection
    net.setInput(blob)
    layer_names = net.getLayerNames()
    output_layers = [layer_names[i - 1] for i in net.getUnconnectedOutLayers()]
    outputs = net.forward(output_layers)

    boxes = []
    confidences = []

    # Iterate over the output layers
    for output in outputs:
        # Iterate over the detected objects
        for detection in output:
            # Extract the class ID and confidence score
            scores = detection[5:]
            class_id = np.argmax(scores)
            confidence = scores[class_id]

            # Check if the detected object is above the confidence threshold
            if confidence > conf_threshold:
                # Compute the bounding box coordinates of the detected object
                center_x = int(detection[0] * w)
                center_y = int(detection[1] * h)
                box_width = int(detection[2] * w)
                box_height = int(detection[3] * h)
                left = int(center_x - box_width / 2)
                top = int(center_y - box_height / 2)

                # Apply non-maximum suppression to remove overlapping boxes
                box = [left, top, box_width, box_height]
                
                boxes.append(box)
                confidences.append(float(confidence))
    
    # Apply non-maximum suppression to remove overlapping boxes
    indices = cv2.dnn.NMSBoxes(boxes, confidences, conf_threshold, nms_threshold)

    # Draw the final bounding boxes on the cropped image
    for i in indices:
        i = i[0]
        box = boxes[i]
        x, y, w, h = box
        cv2.rectangle(crop_img, (x, y), (x + w, y + h), (0, 255, 0), 2)

    # Save the cropped image to a file
    filename = f"crop_{i}.png"
    cv2.imwrite(filename, crop_img)



In [26]:
image_array = []

for i, contour in enumerate(contours):
    print("bassem")
    # Load the input image
    image = cv2.imread(f"crop_{i}.png")

    # Get the original dimensions of the image
    height, width, _ = image.shape

    # Calculate the aspect ratio of the image
    aspect_ratio = width / height

    # Set the desired output size (height or width)
    output_size = 224

    # Calculate the other dimension based on the aspect ratio
    if width > height:
        new_width = output_size
        new_height = int(new_width / aspect_ratio)
    else:
        new_height = output_size
        new_width = int(new_height * aspect_ratio)

    # Resize the image
    resized_image = cv2.resize(image, (new_width, new_height))

    # Create a new blank image with the desired output size
    new_image = np.zeros((output_size, output_size, 3), np.uint8)
    new_image[:, :] = (255, 255, 255)  # fill with black pixels

    # Calculate the coordinates to copy the resized image onto the new image
    x_offset = int((output_size - new_width) / 2)
    y_offset = int((output_size - new_height) / 2)

    # Copy the resized image onto the new image with black pixels
    new_image[y_offset:y_offset+new_height, x_offset:x_offset+new_width] = resized_image

    # Save the final image to a file
    cv2.imwrite(f"resize{i}.png", new_image)

    image = cv2.imread(f"resize{i}.png")
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    thresh = cv2.threshold(gray,0,255,cv2.THRESH_OTSU + cv2.THRESH_BINARY)[1]
    inv = cv2.bitwise_not(thresh)
    seg_img = cv2.imwrite(f"seg_img{i}.png", inv)
    image_array.append(seg_img)

bassem
bassem
bassem


In [27]:
import torchvision.transforms as transforms
from PIL import Image
from PIL import ImageFile
import cv2

results = ""
#Basma
for i in range(len(image_array)):
    input_image = Image.open(f'seg_img{i}.png').convert('RGB')
    # input_image = Image.open('C:/Users/basma/Fourth Year/Graduation_Project/SegmentedDatasetAgain/train/A040/A040_1.png').convert('RGB')
    #Bassem
    # input_image = Image.open('D:/Ahmed Bassem/MIU/Year 4/Graduation Project/Datasets/SegmentedDataset/SegmentedDataset/test/O001/O001_1.png').convert('RGB')

    preprocess = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        # transforms.Pad(50),
    ])
    input_tensor = preprocess(input_image)
    # input_tensor = preprocess(Image.fromarray(i))
    input_batch = input_tensor.unsqueeze(0)
    if torch.cuda.is_available():
        input_batch = input_batch.to('cuda')
        model.to('cuda')

    with torch.no_grad():
        output = model(input_batch)

    # Tensor of shape 1000, with confidence scores over Aegyptos' 1072 classes
    print(output[0])
    # The output has unnormalized scores. To get probabilities, you can run a softmax on it.
    probabilities = torch.nn.functional.softmax(output[0], dim=0)

    # Read the categories
    #Basma
    with open("classes_names.txt", "r") as f:

    #Bassem
    # with open("D:/Ahmed Bassem/MIU\Year 4/Graduation Project/classes_names.txt", "r") as f:
        categories = [s.strip() for s in f.readlines()]
    # Show top categories per image
    top5_prob, top5_catid = torch.topk(probabilities, 5)
    for i in range(top5_prob.size(0)):
        print(categories[top5_catid[i]], top5_prob[i].item())

    top1 = categories[top5_catid[0]]
    print(top1)
    # results = results + top1 + " "
    results += " "+ top1
updated_results = results.replace(" ", "", 1)
    # results.append(top1)
print(updated_results)

tensor([14.6810,  6.4098,  8.2626,  ...,  0.3235,  1.4092,  4.0678])
D021 0.9835072755813599
D022 0.00982186570763588
D023 0.006269935984164476
R005 0.00012702718959189951
T030 0.00011304713552817702
D021
tensor([ 9.7802,  3.1250,  6.2839,  ..., 25.4898, 15.7736, 12.7743])
O001 0.8314805626869202
AA012 0.055264417082071304
N036 0.04990420117974281
F018 0.04530208557844162
D051 0.006555827334523201
O001
tensor([18.9603, 18.5760, 13.6490,  ...,  9.8656,  4.5838,  3.9390])
D055 0.7123855352401733
M014 0.1046474501490593
D054 0.0649421438574791
H007 0.017314428463578224
AA007B 0.016710810363292694
D055
D021 O001 D055


In [13]:
import matching_algorithm as ma
print(ma.dictionary_matching(updated_results))


walk


In [18]:
import matching_algorithm_pronunciation as ma
print(ma.dictionary_matching_pronunciation(updated_results))

بري


In [14]:
import googletrans
from googletrans import *

In [16]:
match = ma.dictionary_matching(updated_results)

In [17]:
translator = googletrans.Translator()
translate=translator.translate(match,dest='arabic')
print(translate.text)

يمشي
