In [1]:
# loaded_model = pickle.load("squeezenetfinetuned.pkl")
import sklearn 
import numpy as np
import joblib
import pickle
import torch

#Basma
# classifer = joblib.load("C:/Users/basma/Fourth Year/Graduation_Project/squeezenetfinetuned.pkl")

#Bassem
# classifer = joblib.load("squeezenetuntrained.pkl")

# model = pickle.load(open('new squeezenet(finetuned).pkl', 'rb'))
model = pickle.load(open('squeezenetLxA_dataset.pkl', 'rb'))
model.eval()

c:\Users\Ahmed B\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: [WinError 127] The specified procedure could not be found
  warn(f"Failed to load image Python extension: {e}")


SqueezeNet(
  (features): Sequential(
    (0): Conv2d(3, 96, kernel_size=(7, 7), stride=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=True)
    (3): Fire(
      (squeeze): Conv2d(96, 16, kernel_size=(1, 1), stride=(1, 1))
      (squeeze_activation): ReLU(inplace=True)
      (expand1x1): Conv2d(16, 64, kernel_size=(1, 1), stride=(1, 1))
      (expand1x1_activation): ReLU(inplace=True)
      (expand3x3): Conv2d(16, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (expand3x3_activation): ReLU(inplace=True)
    )
    (4): Fire(
      (squeeze): Conv2d(128, 16, kernel_size=(1, 1), stride=(1, 1))
      (squeeze_activation): ReLU(inplace=True)
      (expand1x1): Conv2d(16, 64, kernel_size=(1, 1), stride=(1, 1))
      (expand1x1_activation): ReLU(inplace=True)
      (expand3x3): Conv2d(16, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (expand3x3_activation): ReLU(inplace=True)
    )
    (5): Fire(
   

In [4]:
import cv2
import numpy as np


################################################################################################
# Set threshold values for binary image and blob analysis
deleteCounterImage = 0
binary_threshold = 50
blob_min_area = 200

# # Load the input image
# image = cv2.imread("word3.png")

# # Convert the image to grayscale
# gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# # Calculate the image histogram
# hist = cv2.calcHist([gray], [0], None, [256], [0, 256])

# # Check if the histogram contains more than two significant peaks
# significant_peaks = np.sum(hist > 0.1 * np.max(hist))
# is_black_and_white = significant_peaks <= 2

# # Print the result
# if is_black_and_white:
#     print("The image is black and white.")
# else:
#     print("The image is Colored")
################################################################################################
# Load the input image
image = cv2.imread("word4.png")

# Convert image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Removing illumination noise using Adaptive Threshold
thresh = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 51, 25)

# Apply Otsu's thresholding method to get a binary image
_, threshold = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

# Invert the binary image
binary = cv2.bitwise_not(threshold)

# Remove Salt and Pepper Noise
denoised_image = cv2.medianBlur(binary, 3)

# Perform blob analysis
contours, hierarchy = cv2.findContours(denoised_image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Sort contours by x-coordinate and then by y-coordinate
# contours = sorted(contours, key=lambda c: (cv2.boundingRect(c)[0], cv2.boundingRect(c)[1]))
# Sort contours from top to bottom and left to right
contours = sorted(contours, key=lambda c: (cv2.boundingRect(c)[1], cv2.boundingRect(c)[0]))

# threshold_percentage = 0.01  # Adjust this value as needed
# blob_min_area = int(image.shape[0] * image.shape[1] * threshold_percentage)

# Iterate over the sorted contours
for i, contour in enumerate(contours):
    
    # Check if the area of the contour is large enough to be considered an object
    if cv2.contourArea(contour) > blob_min_area:
        # Get bounding box coordinates
        x, y, w, h = cv2.boundingRect(contour)

        # Crop the image using the bounding box coordinates
        crop_img = image[y:y+h, x:x+w]
        # Save the cropped image to a file
        filename = f"crop_{i}.png"
        cv2.imwrite(filename, crop_img)

        

The image is Colored


In [15]:
from PIL import Image, ImageFilter
import glob

image_array = []
image_files = glob.glob("*crop*.png")
for i, image_file in enumerate(image_files):
    
    # print("ana: ",i)
    # Load the input image
    # image1 = cv2.imread("X007.png")
    image1 = cv2.imread(image_file)

    # Get the original dimensions of the image
    height, width, _ = image1.shape

    # Calculate the aspect ratio of the image
    aspect_ratio = width / height

    # Set the desired output size (height or width)
    output_size = 224

    # Calculate the other dimension based on the aspect ratio
    if width > height:
        new_width = output_size
        new_height = int(new_width / aspect_ratio)
    else:
        new_height = output_size
        new_width = int(new_height * aspect_ratio)

    # Resize the image
    resized_image = cv2.resize(image1, (new_width, new_height))

    # Calculate the coordinates to copy the resized image onto the new image
    x_offset = int((output_size - new_width) / 2)
    y_offset = int((output_size - new_height) / 2)

    # Save the resized image to a file
    cv2.imwrite(f"resize{i}.png", resized_image)

    # Load the resized image from file
    resized_image = cv2.imread(f"resize{i}.png")

    # Convert image to grayscale
    gray = cv2.cvtColor(resized_image, cv2.COLOR_BGR2GRAY)
    # do adaptive threshold on gray image
    thresh1 = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 51, 25)
    # Apply Otsu's thresholding method to get a binary image
    thresh2 = cv2.threshold(thresh1, 0, 255, cv2.THRESH_OTSU + cv2.THRESH_BINARY)[1]
    # Invert the binary image
    inv = cv2.bitwise_not(thresh2)
    # Apply median filtering
    denoised_image = cv2.medianBlur(binary, 3)
    # Save the segmented image to a file
    cv2.imwrite(f"seg_img{i}.png", inv)
    # Load the segmented image from file
    seg_img = cv2.imread(f"seg_img{i}.png")

    # Create a new blank image with the desired output size
    new_image = np.zeros((output_size, output_size, 3), np.uint8)
    new_image[:, :] = (0, 0, 0)  # fill with black pixels

    # Copy the segmented image onto the new image with black pixels
    new_image[y_offset:y_offset+new_height, x_offset:x_offset+new_width] = seg_img

    # Save the new image to a file
    cv2.imwrite(f"final{i}.png", new_image)
    deleteCounterImage = deleteCounterImage+1
    # image_array.append(new_image)


In [16]:
import torchvision.transforms as transforms
from PIL import Image
from PIL import ImageFile
import cv2

results = ""
#Basma
for i in range(deleteCounterImage):
    # print(deleteCounterImage)
    input_image = Image.open(f'final{i}.png').convert('RGB')
# input_image = Image.open('C:/Users/basma/Fourth Year/Graduation_Project/SegmentedDatasetAgain/train/A040/A040_1.png').convert('RGB')
#Bassem
# input_image = Image.open('D:/Ahmed Bassem/MIU/Year 4/Graduation Project/Datasets/SegmentedDataset/SegmentedDataset/test/O001/O001_1.png').convert('RGB')

    preprocess = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        # transforms.Pad(50),
    ])
    input_tensor = preprocess(input_image)
    # input_tensor = preprocess(Image.fromarray(i))
    input_batch = input_tensor.unsqueeze(0)
    if torch.cuda.is_available():
        input_batch = input_batch.to('cuda')
        model.to('cuda')

    with torch.no_grad():
        output = model(input_batch)

    # Tensor of shape 1000, with confidence scores over Aegyptos' 1072 classes
    print(output[0])
    # The output has unnormalized scores. To get probabilities, you can run a softmax on it.
    probabilities = torch.nn.functional.softmax(output[0], dim=0)

    # Read the categories
    #Basma
    with open("classes_names_LxA.txt", "r") as f:

    #Bassem
    # with open("D:/Ahmed Bassem/MIU\Year 4/Graduation Project/classes_names.txt", "r") as f:
        categories = [s.strip() for s in f.readlines()]
    # Show top categories per image
    top5_prob, top5_catid = torch.topk(probabilities, 5)
    for i in range(top5_prob.size(0)):
        print(categories[top5_catid[i]], top5_prob[i].item())

    top1 = categories[top5_catid[0]]
    print(top1)

    class_name = 'D021'
    class_index = categories.index(class_name)
    class_prob = probabilities[class_index] * 100
    print(f"Percentage of confidence for {class_name}: {class_prob:.2f}%")

    # results = results + top1 + " "
    results += " "+ top1
    updated_results = results.replace(" ", "", 1)
        # results.append(top1)
    print(updated_results)
    choose_dictionary_list=deleteCounterImage-1
    print(choose_dictionary_list)

tensor([30.1412,  5.2579,  3.3973,  ...,  0.9228,  0.4880,  0.8590])
F004 0.9133402109146118
D055 0.06149863451719284
V028 0.018693381920456886
L002 0.0021536550484597683
U022 0.0016547832638025284
F004
Percentage of confidence for D021: 0.00%
F004
2
tensor([14.3598, 14.5042, 10.4926,  ...,  0.6460,  0.9081,  0.6367])
S014A 0.5319290161132812
AA012 0.28926658630371094
O001 0.10063762962818146
M039 0.03779811039566994
F004 0.017189670354127884
S014A
Percentage of confidence for D021: 0.00%
F004 S014A
2
tensor([11.5215,  7.3488,  1.7157,  ...,  0.6869,  0.4944,  0.3185])
D021 0.9990808963775635
U004 0.0002796726766973734
I009 0.0002740708878263831
L002 0.00024076434783637524
M003 3.679895235109143e-05
D021
Percentage of confidence for D021: 99.91%
F004 S014A D021
2


In [8]:
# for i in range(deleteCounterImage):
#     print(i)
#     if(updated_results[i] == 'A'):
#         print("A")
#         print(i)
        

0
1
2


In [17]:
# import matching_algorithm as ma
# print(ma.dictionary_matching(updated_results))

##NEW CODE
import matching_algorithm3 as ma
print(ma.dictionary_matching(updated_results,choose_dictionary_list))


[(['O001 D021 D054'], 69, 'walk'), (['O034 V031 D021'], 69, 'Seker or Soker'), (['S029 D066 F046A'], 60, 'Write'), (['V031 G001 A002'], 55, 'Think'), (['O034 X001 B001'], 55, 'Women')]
(['O001 D021 D054'], 69, 'walk')
walk


In [6]:
import os

# Delete previously created images
cropImageRemovals = glob.glob("*crop*.png")
for i in range(deleteCounterImage):
    removeCrop = cropImageRemovals
    removeSegImg = f"seg_img{i}.png"
    removeFinal = f"final{i}.png"
    removeResize = f"resize{i}.png"
    try:
        os.remove(removeCrop[i])
        os.remove(removeSegImg)
        os.remove(removeFinal)
        os.remove(removeResize)
    except FileNotFoundError:
        pass

In [6]:
import matching_algorithm_pronunciation as ma
print(ma.dictionary_matching_pronunciation(updated_results))

لا يوجد صوت


In [7]:
import googletrans
from googletrans import *

In [8]:
match = ma.dictionary_matching(updated_results)

AttributeError: module 'matching_algorithm_pronunciation' has no attribute 'dictionary_matching'

In [9]:
translator = googletrans.Translator()
translate=translator.translate(match,dest='arabic')
print(translate.text)

NameError: name 'match' is not defined